# Step 1: Build stage
FROM node:14.16.0-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# CMD ["npm", "start"]
RUN npm run build

# Step 2: Production
# nginx is a webserver => 1.12-alpine is based on alpine Linux and super small!
FROM nginx:1.12-alpine AS production-stage
RUN addgroup app && adduser -S -G app app
USER app
COPY --from=build-stage /app/build /usr/share/nginx/html
# EXPOSE 3000 
EXPOSE 80
ENTRYPOINT [ "nginx", "-g","daemon off;" ]