version: "3.8"

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
        # - ./$(pwd):/app/node_modules
        # - /(C:\Data\DCI-WebEntwicklung\assignement\DOCKER\Mosh-Hamedani\vidly\backend):/app
        # - /app/package*.json
        # - /app/node_modules
        # - ./backend:/app/node_modules
        # - ./backend:/app
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
