version: "3.8"

services:
  web:
    # build: ./frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      # - 80:3000
      - 80:80
    restart: unless-stopped
    # volumes:
    #  - ./frontend:/app
  # web-tests:
  #   image: vidly-web
  #   #    ports:
  #   #      - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #   command: npm test
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    # volumes:
    #   - ./backend:/app
    # command: ./wait-for db:27017 && migrate-mongo up && npm start
    command: ./docker-entrypoint.sh
    restart: unless-stopped

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
    restart: unless-stopped

volumes:
  vidly:
