version: "3.8"

services:
  web:
    build: ./frontend
    ports:
      - 3003:3003
  api:
    build: ./backend
    ports:
      - 3002:3002
    environment:
      DB_URL: mongodb://db/vidly
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
